name: Build Town Of Us downloader

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./scripts

    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r '*/scripts/requirement.txt'
#         pip install pyinstaller


#       - name: build with pyinstaller
#         run: |
#            pyinstaller --onefile --noconsole --icon res/among_us.ico --name "Town Of Us" main.py

